#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : retry_decorator
Version  : 1.1.0
Release  : 29
URL      : https://files.pythonhosted.org/packages/95/7a/807ac21749ecd26ae3337c3069ed6ac8658b9fbc85f109e419a812b18ab7/retry_decorator-1.1.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/95/7a/807ac21749ecd26ae3337c3069ed6ac8658b9fbc85f109e419a812b18ab7/retry_decorator-1.1.0.tar.gz
Summary  : Retry Decorator
Group    : Development/Tools
License  : MIT
Requires: retry_decorator-license = %{version}-%{release}
Requires: retry_decorator-python = %{version}-%{release}
Requires: retry_decorator-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
Usage
-----

Retry decorator

::

    #!/usr/bin/env python

    from __future__ import print_function
    from retry_decorator import *

    @retry(Exception, tries = 3, timeout_secs = 0.1)
    def test_retry():
        import sys
        print('hello', file = sys.stderr)
        raise Exception('Testing retry')

    if __name__ == '__main__':
        try:
            test_retry()
        except Exception as e:
            print('Received the last exception')


Contribute
---------------
I would love for you to fork and send me pull request for this project. Please contribute.

%package license
Summary: license components for the retry_decorator package.
Group: Default

%description license
license components for the retry_decorator package.


%package python
Summary: python components for the retry_decorator package.
Group: Default
Requires: retry_decorator-python3 = %{version}-%{release}

%description python
python components for the retry_decorator package.


%package python3
Summary: python3 components for the retry_decorator package.
Group: Default
Requires: python3-core
Provides: pypi(retry_decorator)

%description python3
python3 components for the retry_decorator package.


%prep
%setup -q -n retry_decorator-1.1.0
cd %{_builddir}/retry_decorator-1.1.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1583220057
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/retry_decorator
cp %{_builddir}/retry_decorator-1.1.0/LICENSE.txt %{buildroot}/usr/share/package-licenses/retry_decorator/4a87a559be6eb9023bf0b0e3bd37a71f7b6d1f9e
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/retry_decorator/4a87a559be6eb9023bf0b0e3bd37a71f7b6d1f9e

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
