#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : retry_decorator
Version  : 1.1.0
Release  : 24
URL      : https://files.pythonhosted.org/packages/95/7a/807ac21749ecd26ae3337c3069ed6ac8658b9fbc85f109e419a812b18ab7/retry_decorator-1.1.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/95/7a/807ac21749ecd26ae3337c3069ed6ac8658b9fbc85f109e419a812b18ab7/retry_decorator-1.1.0.tar.gz
Summary  : Retry Decorator
Group    : Development/Tools
License  : MIT
Requires: retry_decorator-license = %{version}-%{release}
Requires: retry_decorator-python = %{version}-%{release}
Requires: retry_decorator-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
Usage
        -----
        
        Retry decorator

%package license
Summary: license components for the retry_decorator package.
Group: Default

%description license
license components for the retry_decorator package.


%package python
Summary: python components for the retry_decorator package.
Group: Default
Requires: retry_decorator-python3 = %{version}-%{release}

%description python
python components for the retry_decorator package.


%package python3
Summary: python3 components for the retry_decorator package.
Group: Default
Requires: python3-core

%description python3
python3 components for the retry_decorator package.


%prep
%setup -q -n retry_decorator-1.1.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1546112373
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/retry_decorator
cp LICENSE.txt %{buildroot}/usr/share/package-licenses/retry_decorator/LICENSE.txt
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/retry_decorator/LICENSE.txt

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
